<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<Folder Include="Interfaces\IServices\" />
		<Folder Include="Interfaces\IUnitOfWork\" />
		<Folder Include="Services\" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Event_Management.Domain\Event_Management.Domain.csproj" />
	</ItemGroup>
	
	

</Project>