<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Msql\" />
    <Folder Include="Entities\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="C:\Users\DELL\Downloads\Event_Managements_Database.sql" Link="Msql\Event_Managements_Database.sql" />
  </ItemGroup>

</Project>
